# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models

from modules.utils.functions import generate_orderable_version_number


def create_version_order(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    for note in Note.objects.all():
        note.release_version_order = generate_orderable_version_number(
            note.release_version,
        )
        note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['project__name', '-release_version']},
        ),
        migrations.AddField(
            model_name='note',
            name='release_version_order',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(create_version_order, lambda _, __: None),
    ]
